### ISSUE TITLE
How to exclude certain routes

### ISSUE THREAD

**Issue by trondhindenes** [opentracing-contrib/python-flask#13]
The example setup works well, however I'm trying to figure out if it's possible to use an exclusion filter to remove http routes I don't want tracing on. For example, `/health` endpoints are not interesting to get tracing info on.

It this possible?

**Comment by ror6ax** [comment]
You'll have to use `@tracer.trace` decorator per endpoint. See https://github.com/opentracing-contrib/python-flask#trace-individual-requests
