### ISSUE TITLE
Add examples with blueprints usage.

### ISSUE THREAD

**Issue by ror6ax** [opentracing-contrib/python-flask#16]
Most production flask apps would use blueprints. Add documentation to show how to achieve tracing of such application layout.

**Comment by william20111** [comment]
Has anyone used this particular setup? Im working with blueprints and wondering what best practice is for setting up tracing with them using that project structure.

**Comment by roachlord** [comment]
This can be implemented by passing the flask blueprint to the `FlaskTracing.__init__` method instead of the `app` and `trace_all_requests=True`

**Comment by ptmcg** [comment]
This package is no longer being maintained, users should migrate to the `opentelemetry-api` package.

Closing.
