### ISSUE TITLE
It seems FlaskTracer does not set span.kind tag on the server span

### ISSUE THREAD

**Issue by yurishkuro** [opentracing-contrib/python-flask#19]

**Comment by carlosalberto** [comment]
Closing as #21 fixed this.

**Comment by yurishkuro** [comment]
Is there a new release coming?

**Comment by carlosalberto** [comment]
Yes! ;) This week (had expected to do it last week but was too packed)

**Comment by carlosalberto** [comment]
For reference, I will be merging the `v1.0.0` branch
