### ISSUE TITLE
scope_manager not accessable via opentracing

### ISSUE THREAD

**Issue by jendrikjoe** [opentracing-contrib/python-flask#44]
In the opentracing API the scope manager is stored in the property [`_scope_manager`](https://github.com/opentracing/opentracing-python/blob/7d2e62b5999d3cdec9a9c2720a34a1d11f425461/opentracing/tracer.py#L36) and can be accessed as [`scope_manager`](https://github.com/opentracing/opentracing-python/blob/7d2e62b5999d3cdec9a9c2720a34a1d11f425461/opentracing/tracer.py#L43). 
Currently, the property `_scope_manager` is not set in the `FlaskTracing` class. This leads to issues with opentracing instrumentation that needs access to it, e.g. the boto3 part of the [https://github.com/uber-common/opentracing-python-instrumentation](opentracing-python-instrumentation). (When I have more time, I will try to add a minimal example where failures actually occur.)

I could imagine two fixes to this a) adding 
```python
@property 
def _scope_manager(self):
    return self.tracer._scopemanager
```
or b) explicitly doing:
```python
self._scope_manager = self.tracer.scope_manager
```
in the initializer. 
Happy to write the PR for this, if you provide me your preferences :slightly_smiling_face:

**Comment by yurishkuro** [comment]
I am surprised `FlaskTracing` extends `opentracing.Trace`, it seems unnecessary, since it allows access to the tracer via `tracer()` property. I would not recommend using `FlaskTracing` as a replacement for `Tracer`, especially since the real thing is available anyway.

**Comment by ptmcg** [comment]
This package is no longer being maintained, users should migrate to the `opentelemetry-api` package.

Closing.
