### ISSUE TITLE
I mean is not None?

### ISSUE THREAD

**Issue by ivnminin** [opentracing-contrib/python-flask#52]
https://github.com/opentracing-contrib/python-flask/blob/c7270ca4c6ac9c5189c45c60714afd582af50087/tests/test_flask_tracing.py#L225

**Comment by ivngithub** [comment]
Why are we checking code 200 in this test? There should be a 500 code.

**Comment by ptmcg** [comment]
This package is no longer being maintained, users should migrate to the `opentelemetry-api` package.

Closing.
