### ISSUE TITLE
opentracing setup version

### ISSUE THREAD

**Issue by ChristopheDaSilva** [opentracing-contrib/python-flask#9]
Hi,

opentracing 1.3 can run on python 3, 1.2 and below he can't.

In the setup, 'opentracing>=1.1,<1.2' can be upgrade or there is some issue?

Regards,

**Comment by ror6ax** [comment]
I don't think that this requirement is still valid. I'll check and confirm that. 

Using the project from Python 3 is blocked until https://github.com/jaegertracing/jaeger-client-python/issues/59 is merged, though.

**Comment by zgfh** [comment]
@ror6ax  jaegertracing/jaeger-client-python#59 is merged,can weupgrade the setup ? 
becase I can not install jaeger-client-python (need opentracing>=1.2.2,<2) and flask-opentracing(opentracing>=1.1,<1.2) both

**Comment by ror6ax** [comment]
@zgfh - sure thing, I was planning to to that.

**Comment by ror6ax** [comment]
Hi guys, I've released version 0.2.0 with new version of libs baked in. Works fine for me, please let me know you're happy to close this. @zgfh @ChristopheDaSilva

**Comment by zgfh** [comment]
@ror6ax thanks a lot!
but i have give up use jaege,😄because this: https://github.com/jaegertracing/jaeger-client-python/issues/165

**Comment by ror6ax** [comment]
I'm closing this up as there are no issues regarding versioning reported any more.
